# Generated by Django 5.2.7 on 2025-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montruc',
            name='path',
            field=models.FileField(upload_to='trucs/'),
        ),
    ]
